### ISSUE TITLE
AttributeError with Tetrarch - Negative Noise

### ISSUE THREAD

**Issue by SimonIT** [elmoiv/azapi#13]
[Tetrarch - Negative Noise](https://www.azlyrics.com/lyrics/tetrarch/negativenoise.html)

```
AttributeError: 'NoneType' object has no attribute 'strip'
    lyrics = api.getLyrics(url=result_song["url"])
  File "azapi\azapi.py", line 88, in getLyrics
    self.lyrics = lyrics.strip()
```

The source of the error is probably the non existing lyrics

**Comment by elmoiv** [comment]
It is working fine with latest version of azapi (3.0.6)

Can you please update it to v3.0.6, retry and inform me about any issues?

**Comment by SimonIT** [comment]
Ah sorry, my bad. Didn't check the version of the error report. It happened with 3.0.2
